kind: pipeline
name: default

steps:
  - name: docker
    image: plugins/docker
    environment:
      PUBLIC_FIREBASE_API_KEY:
        from_secret: SW_PUBLIC_FIREBASE_API_KEY
      PUBLIC_FIREBASE_AUTH_DOMAIN:
        from_secret: SW_PUBLIC_FIREBASE_AUTH_DOMAIN
      PUBLIC_FIREBASE_PROJECT_ID:
        from_secret: SW_PUBLIC_FIREBASE_PROJECT_ID
      PUBLIC_FIREBASE_STORAGE_BUCKET:
        from_secret: SW_PUBLIC_FIREBASE_STORAGE_BUCKET
      PUBLIC_FIREBASE_MESSAGING_SENDER_ID:
        from_secret: SW_PUBLIC_FIREBASE_MESSAGING_SENDER_ID
      PUBLIC_FIREBASE_APP_ID:
        from_secret: SW_PUBLIC_FIREBASE_APP_ID
      PUBLIC_FIREBASE_MEASUREMENT_ID:
        from_secret: SW_PUBLIC_FIREBASE_MEASUREMENT_ID
      PUBLIC_MAINTENANCE:
        from_secret: SW_PUBLIC_MAINTENANCE
      SECRET_FIREBASE_SERVICE_KEY:
        from_secret: SW_FIREBASE_SERVICE_KEY
    settings:
      registry: registry.gitlab.com
      username:
        from_secret: docker_registry_username
      password:
        from_secret: docker_registry_password
      repo: registry.gitlab.com/codegiik/studentsweek
      build_args_from_env:
        [
          SECRET_FIREBASE_SERVICE_KEY,
          PUBLIC_FIREBASE_API_KEY,
          PUBLIC_FIREBASE_AUTH_DOMAIN,
          PUBLIC_FIREBASE_PROJECT_ID,
          PUBLIC_FIREBASE_STORAGE_BUCKET,
          PUBLIC_FIREBASE_MESSAGING_SENDER_ID,
          PUBLIC_FIREBASE_APP_ID,
          PUBLIC_FIREBASE_MEASUREMENT_ID
        ]
      auto_tag: true
