FROM node:current-slim AS base

FROM base AS builder

WORKDIR /app
COPY . .

ARG PUBLIC_FIREBASE_API_KEY
ARG PUBLIC_FIREBASE_AUTH_DOMAIN
ARG PUBLIC_FIREBASE_PROJECT_ID
ARG PUBLIC_FIREBASE_STORAGE_BUCKET
ARG PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG PUBLIC_FIREBASE_APP_ID
ARG PUBLIC_FIREBASE_MEASUREMENT_ID
ARG PUBLIC_MAINTENANCE
ARG SECRET_FIREBASE_SERVICE_KEY

ENV PUBLIC_FIREBASE_API_KEY=$PUBLIC_FIREBASE_API_KEY
ENV PUBLIC_MAINTENANCE=$PUBLIC_MAINTENANCE
ENV PUBLIC_FIREBASE_AUTH_DOMAIN=$PUBLIC_FIREBASE_AUTH_DOMAIN
ENV PUBLIC_FIREBASE_PROJECT_ID=$PUBLIC_FIREBASE_PROJECT_ID
ENV PUBLIC_FIREBASE_STORAGE_BUCKET=$PUBLIC_FIREBASE_STORAGE_BUCKET
ENV PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV PUBLIC_FIREBASE_APP_ID=$PUBLIC_FIREBASE_APP_ID
ENV PUBLIC_FIREBASE_MEASUREMENT_ID=$PUBLIC_FIREBASE_MEASUREMENT_ID
ENV SECRET_FIREBASE_SERVICE_KEY=$SECRET_FIREBASE_SERVICE_KEY

RUN apt-get update -y
RUN apt-get install jq -y

RUN corepack pnpm install --prefer-frozen-lockfile

RUN corepack pnpm --filter web build

# Open Issues npm/cli#4967, pnpm/pnpm#3746 (for workspaces:*), pnpm/pnpm#881
RUN jq 'del(.devDependencies)' web/package.json > web/package-prod.json

FROM base AS runner 

WORKDIR /app

COPY --from=builder /app/web/build ./
COPY --from=builder /app/web/package-prod.json ./package.json

RUN corepack pnpm i --prod 

EXPOSE 3000

CMD ["node", "index.js"]
