FROM node:current-slim AS builder

RUN npm i -g pnpm

WORKDIR /app
COPY . .

RUN echo $PUBLIC_FIREBASE_APP_ID

ARG PUBLIC_FIREBASE_API_KEY
ARG PUBLIC_FIREBASE_AUTH_DOMAIN
ARG PUBLIC_FIREBASE_PROJECT_ID
ARG PUBLIC_FIREBASE_STORAGE_BUCKET
ARG PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ARG PUBLIC_FIREBASE_APP_ID
ARG PUBLIC_FIREBASE_MEASUREMENT_ID
ARG PUBLIC_MAINTENANCE
ARG SECRET_FIREBASE_SERVICE_KEY

ENV PUBLIC_FIREBASE_API_KEY=$PUBLIC_FIREBASE_API_KEY
ENV PUBLIC_MAINTENANCE=$PUBLIC_MAINTENANCE
ENV PUBLIC_FIREBASE_AUTH_DOMAIN=$PUBLIC_FIREBASE_AUTH_DOMAIN
ENV PUBLIC_FIREBASE_PROJECT_ID=$PUBLIC_FIREBASE_PROJECT_ID
ENV PUBLIC_FIREBASE_STORAGE_BUCKET=$PUBLIC_FIREBASE_STORAGE_BUCKET
ENV PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$PUBLIC_FIREBASE_MESSAGING_SENDER_ID
ENV PUBLIC_FIREBASE_APP_ID=$PUBLIC_FIREBASE_APP_ID
ENV PUBLIC_FIREBASE_MEASUREMENT_ID=$PUBLIC_FIREBASE_MEASUREMENT_ID
ENV SECRET_FIREBASE_SERVICE_KEY=$SECRET_FIREBASE_SERVICE_KEY

RUN pnpm install --prefer-frozen-lockfile

RUN pnpm build

FROM node:current-slim

WORKDIR /app
COPY --from=builder /app/build ./
COPY --from=builder /app/package.json ./

RUN npm i --omit=dev 

EXPOSE 3000

CMD ["node", "index.js"]
