version: "3.8"

services:
  frontend:
    image: registry.gitlab.com/codegiik/studentsweek:latest
    ports:
      - 3000:3000
    build:
      context: ./
      args:
        - PUBLIC_FIREBASE_API_KEY=$PUBLIC_FIREBASE_API_KEY
        - PUBLIC_MAINTENANCE=$PUBLIC_MAINTENANCE
        - PUBLIC_FIREBASE_AUTH_DOMAIN=$PUBLIC_FIREBASE_AUTH_DOMAIN
        - PUBLIC_FIREBASE_PROJECT_ID=$PUBLIC_FIREBASE_PROJECT_ID
        - PUBLIC_FIREBASE_STORAGE_BUCKET=$PUBLIC_FIREBASE_STORAGE_BUCKET
        - PUBLIC_FIREBASE_MESSAGING_SENDER_ID=$PUBLIC_FIREBASE_MESSAGING_SENDER_ID
        - PUBLIC_FIREBASE_APP_ID=$PUBLIC_FIREBASE_APP_ID
        - PUBLIC_FIREBASE_MEASUREMENT_ID=$PUBLIC_FIREBASE_MEASUREMENT_ID
        - SECRET_FIREBASE_SERVICE_KEY=$SECRET_FIREBASE_SERVICE_KEY
    env_file: .env
    restart: unless-stopped
